### ISSUE TITLE
master branch, failing to compile on linux on 28th June 2014

### ISSUE THREAD

**Issue by LeForgeron** [POV-Ray/povray#29]
The head of master fails to compile on linux Ubuntu 14.04 with g++ 4.8 (and it's probably not the only system to fails).
1. In colour.h, missing include of <limits> to get access to std::numeric_limits 
   
   http://www.cplusplus.com/reference/limits/numeric_limits/
2. In colour.h, circa line 1059, there is no mFilter for  
   inline GenericRGBColour<T> TransmittedColour() const
3. in express.cpp, many error about template:
   error: dependent-name ‘MAP_T:: Entry’ is parsed as a non-type, but instantiation yields a type
      MAP_T::Entry        Temp_Ent;
      ^
   backend/parser/express.cpp:3200:5: note: say ‘typename MAP_T:: Entry’ if a type is meant
   backend/parser/express.cpp:3201:5: error: dependent-name ‘MAP_T:: Vector’ is parsed as a non-type, but instantiation yields a type
    MAP_T::Vector       tempList;
    ^
   backend/parser/express.cpp:3201:5: note: say ‘typename MAP_T:: Vector’ if a type is meant

---

there is probably more issues, but so far it is already broken enough.

I guess that the warning in colour.h is wanted:
./base/colour.h:1225:73: warning: friend declaration ‘pov_base::GenericColour<T> pov_base::ToMathColour(const pov_base::GenericRGBColour<T>&)’ declares a non-template function [-Wnon-template-friend]
         friend GenericColour ToMathColour(const GenericRGBColour<T>& col);
