### ISSUE TITLE
macOS build failure for 3.7.0.5

### ISSUE THREAD

**Issue by ilovezfs** [POV-Ray/povray#341]
```
Making install in unix
clang++ -DHAVE_CONFIG_H -I. -I..  -I.. -I../source -I../source -I../source/backend -I../source/base -I../source/frontend -I../vfe -I../vfe/unix -pthread -I/usr/local/opt/boost/include  -pipe -Wno-multichar -Wno-write-strings -O3 -ffast-math -march=native -D_THREAD_SAFE -c -o disp_sdl.o disp_sdl.cpp
clang++ -DHAVE_CONFIG_H -I. -I..  -I.. -I../source -I../source -I../source/backend -I../source/base -I../source/frontend -I../vfe -I../vfe/unix -pthread -I/usr/local/opt/boost/include  -pipe -Wno-multichar -Wno-write-strings -O3 -ffast-math -march=native -D_THREAD_SAFE -c -o disp_text.o disp_text.cpp
clang++  -pipe -Wno-multichar -Wno-write-strings -O3 -ffast-math -march=native -D_THREAD_SAFE  -L/usr/local/opt/boost/lib -o povray disp_sdl.o disp_text.o ../vfe/libvfe.a ../source/libpovray.a -ltiff -ljpeg -lpng -lz -lm -lboost_thread-mt  -D_THREAD_SAFE   
Undefined symbols for architecture x86_64:
  "boost::system::generic_category()", referenced from:
      boost::mutex::mutex() in libvfe.a(unixconsole.o)
      boost::unique_lock<boost::mutex>::lock() in libvfe.a(unixconsole.o)
      boost::mutex::lock() in libvfe.a(unixconsole.o)
      boost::thread::start_thread() in libvfe.a(unixconsole.o)
      boost::condition_variable::condition_variable() in libvfe.a(unixconsole.o)
      boost::thread::join() in libvfe.a(vfesession.o)
      void boost::condition_variable_any::wait<boost::unique_lock<boost::mutex> >(boost::unique_lock<boost::mutex>&) in libvfe.a(vfesession.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [povray] Error 1
make: *** [install-recursive] Error 1
```
Boost 1.66.0
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/15696/version=high_sierra/testReport/junit/brew-test-bot/high_sierra/install_povray/

**Comment by c-lipka** [comment]
Uh... yeah. That says virtually nothing. Judging from the error message, _something_ in boost 1.66.0 (which POV-Ray v3.7.0.5 happens to rely on) appears to be broken.

**Comment by c-lipka** [comment]
Please try with boost 1.65.1, and if that works, please turn to the authors of the boost library for support.

**Comment by ilovezfs** [comment]
I'll try with 1.65 but I think you're just missing a `-lboost_system` in one of the Makefiles.

**Comment by ilovezfs** [comment]
Yes it works with 1.65.1 and notice
```
clang++  -pipe -Wno-multichar -Wno-write-strings -O3 -ffast-math -march=native -D_THREAD_SAFE  -L/usr/local/opt/boost/lib -o povray disp_sdl.o disp_text.o ../vfe/libvfe.a ../source/libpovray.a -ltiff -ljpeg -lpng -lz -lm -lboost_thread-mt  -D_THREAD_SAFE   -lboost_system
```
whereas with 1.66 the -lboost_system is missing.

**Comment by ilovezfs** [comment]
Yeah so the issue is that
```
iMac-TMP:~ joe$ clang++ -o conftest  -D_THREAD_SAFE   -pthread -I/usr/local/opt/boost/include  -L/usr/local/opt/boost/lib conftest.cpp -lboost_thread-mt  -D_THREAD_SAFE 
Undefined symbols for architecture x86_64:
  "boost::system::system_category()", referenced from:
      ___cxx_global_var_init.2 in conftest-11665f.o
  "boost::system::generic_category()", referenced from:
      ___cxx_global_var_init in conftest-11665f.o
      ___cxx_global_var_init.1 in conftest-11665f.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
iMac-TMP:~ joe$ brew rm boost
Warning: /usr/local/Cellar/boost/1.65.1_1 is required by redex 2017.10.31, which is currently installed.
You can silence this warning with:
  brew uninstall --ignore-dependencies boost
Uninstalling /usr/local/Cellar/boost/1.65.1_1... (12,681 files, 413MB)
boost 1.66.0 1 is still installed.
Remove all versions with `brew uninstall --force boost`.
iMac-TMP:~ joe$ tcd core
iMac-TMP:homebrew-core joe$ git checkout origin/master -- Formula/boost.rb
iMac-TMP:homebrew-core joe$ brew install boost
Warning: boost 1.66.0 is already installed, it's just not linked.
You can use `brew link boost` to link this version.
iMac-TMP:homebrew-core joe$ brew link boost
Linking /usr/local/Cellar/boost/1.66.0... 133 symlinks created
iMac-TMP:homebrew-core joe$ cd -
/Users/joe
iMac-TMP:~ joe$ clang++ -o conftest  -D_THREAD_SAFE   -pthread -I/usr/local/opt/boost/include  -L/usr/local/opt/boost/lib conftest.cpp -lboost_thread-mt  -D_THREAD_SAFE 
iMac-TMP:~ joe$ 
```
where conftest.cpp is
```
#include <boost/thread/thread.hpp>

int
main ()
{
boost::defer_lock_t(); return 0;
  ;
  return 0;
}
```
and compiles successfully without -lboost_system with 1.66 but fails without -lboost_system with 1.65. So configure decides to try again with -lboost_system with 1.65 whereas it already thinks everything is good to go on 1.66.

**Comment by ilovezfs** [comment]
So we need to improve the test program here https://github.com/POV-Ray/povray/blob/master/unix/configure.ac#L341-L345 so that it fails on 1.66 when you haven't thrown in -lboost_system.

**Comment by c-lipka** [comment]
In `configure.ac`, can you try changing line 344 to:

    [[boost::mutex m; boost::defer_lock_t(); return 0;]])],

**Comment by ilovezfs** [comment]
Yup that works :)
